




androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigation"}
lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-compose", version = "2.9.4"}
lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version = "2.9.4"}


